# Generated by Django 2.1.2 on 2018-12-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='image',
            field=models.ImageField(default='DUMMIY', upload_to=''),
            preserve_default=False,
        ),
    ]
